[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/portfolio/*"
  to = "/portfolio/:splat.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[context.production.environment]
  INSTAGRAM_ACCESS_TOKEN = ""
  FORMSPREE_ENDPOINT = ""
  MAILERLITE_API_KEY = ""
  GA_TRACKING_ID = ""

[context.deploy-preview.environment]
  INSTAGRAM_ACCESS_TOKEN = ""
  FORMSPREE_ENDPOINT = ""
  MAILERLITE_API_KEY = ""
  GA_TRACKING_ID = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://www.google-analytics.com https://api.instagram.com https://formspree.io https://api.mailerlite.com;"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"