#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

console.log('🔧 Building environment configuration...');

// Environment variables configuration
const envConfig = {
  INSTAGRAM_ACCESS_TOKEN: process.env.INSTAGRAM_ACCESS_TOKEN || '',
  FORMSPREE_ENDPOINT: process.env.FORMSPREE_ENDPOINT || '',
  MAILERLITE_API_KEY: process.env.MAILERLITE_API_KEY || '',
  GA_TRACKING_ID: process.env.GA_TRACKING_ID || '',
  NODE_ENV: process.env.NODE_ENV || 'production'
};

// Create environment configuration file
const envConfigPath = path.join(__dirname, '../js/config/environment.js');
const envConfigContent = `// Auto-generated environment configuration
// Do not edit this file directly - it's generated during build

export const ENV_CONFIG = ${JSON.stringify(envConfig, null, 2)};

export const isDevelopment = () => ENV_CONFIG.NODE_ENV === 'development';
export const isProduction = () => ENV_CONFIG.NODE_ENV === 'production';

// API endpoints
export const API_ENDPOINTS = {
  instagram: 'https://graph.instagram.com/me/media',
  formspree: ENV_CONFIG.FORMSPREE_ENDPOINT,
  mailerlite: 'https://api.mailerlite.com/api/v2/subscribers',
  analytics: 'https://www.google-analytics.com/mp/collect'
};

// Feature flags
export const FEATURES = {
  instagram: !!ENV_CONFIG.INSTAGRAM_ACCESS_TOKEN,
  newsletter: !!ENV_CONFIG.MAILERLITE_API_KEY,
  analytics: !!ENV_CONFIG.GA_TRACKING_ID,
  contactForm: !!ENV_CONFIG.FORMSPREE_ENDPOINT
};
`;

// Ensure config directory exists
const configDir = path.dirname(envConfigPath);
if (!fs.existsSync(configDir)) {
  fs.mkdirSync(configDir, { recursive: true });
}

// Write environment configuration
fs.writeFileSync(envConfigPath, envConfigContent);

console.log('✅ Environment configuration built successfully');
console.log('📍 Configuration written to:', envConfigPath);

// Log feature status
console.log('\n🎯 Feature Status:');
console.log(`   Instagram Integration: ${envConfig.INSTAGRAM_ACCESS_TOKEN ? '✅ Enabled' : '❌ Disabled'}`);
console.log(`   Contact Forms: ${envConfig.FORMSPREE_ENDPOINT ? '✅ Enabled' : '❌ Disabled'}`);
console.log(`   Newsletter: ${envConfig.MAILERLITE_API_KEY ? '✅ Enabled' : '❌ Disabled'}`);
console.log(`   Analytics: ${envConfig.GA_TRACKING_ID ? '✅ Enabled' : '❌ Disabled'}`);

// Validate critical environment variables for production
if (process.env.NODE_ENV === 'production') {
  const missingVars = [];
  
  if (!envConfig.FORMSPREE_ENDPOINT) missingVars.push('FORMSPREE_ENDPOINT');
  if (!envConfig.GA_TRACKING_ID) missingVars.push('GA_TRACKING_ID');
  
  if (missingVars.length > 0) {
    console.warn('\n⚠️  Warning: Missing critical environment variables for production:');
    missingVars.forEach(varName => console.warn(`   - ${varName}`));
    console.warn('   Some features may not work correctly.');
  }
}